tango_with_django_project/rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^about/$',views.about,name='about'),
    url(r'category/(?P<category_name_slug>[\w\-]+)/$',views.show_category,name='show_category'),
    url(r'^add_category/$',views.add_category,name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',views.add_page,name='add_page'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.user_login,name='login'),
    url(r'restricted/', views.restricted, name='restricted'),
    url(r'^logout/$',views.user_logout,name='logout'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from rango import views
from django.conf import settings



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^rango/',include('rango.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^search/', include('haystack.urls')),
]

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
# Create your models here.
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128,unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(blank=True,unique=True)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(Category,self).save(*args,**kwargs)


    class Meta:
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images',blank=True)

    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import  Page, Category,UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(),initial=0,required=False)
    likes = forms.IntegerField(widget=forms.HiddenInput(),initial=0,required=False)
    slug = forms.CharField(widget=forms.HiddenInput(),required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(),initial=0,required=False)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://') and not url.startswith('https://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            return cleaned_data

    class Meta:
        model=Page
        exclude = ('category',)
        #fields = ('title','url','views')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('website','picture')

tango_with_django_project/rango/views.py
from django.shortcuts import render

# Create your views here.

#from django.http import HttpResponse
from rango.models import Category,Page
from rango.forms import  CategoryForm,PageForm,UserForm,UserProfileForm
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime


def get_server_side_cookie(request,cookie,default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


'''
def visitor_cookie_handler(request,response):
    visits_cookie = int(request.COOKIES.get('visits','1'))
    last_visit_cookie = request.COOKIES.get('last_visit',str(datetime.now()))
    visits = visits_cookie
    last_visit = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit).seconds > 0:
        visits = visits_cookie + 1
        response.set_cookie('last_visit',str(datetime.now()))
    else:
        response.set_cookie('last_visit',last_visit_cookie)
    response.set_cookie('visits',visits)
'''


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request,'visits','1'))
    last_visit_cookie = get_server_side_cookie(request,'last_visit',str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).seconds > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits



def index(request):
    request.session.set_test_cookie()
    #return HttpResponse('Rango says hey there partner!')
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories':category_list,'pages':page_list}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request,'rango/index.html',context_dict)
    #response = render(request, 'rango/index.html', context_dict)
    #visitor_cookie_handler(request, response)
    return response

def about(request):
    context_dict = {'your_name':'dongjie','method':request.method,'user':request.user}
    visits = get_server_side_cookie(request,'visits','1')
    last_visit = get_server_side_cookie(request,'last_visit',str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit[:-7], '%Y-%m-%d %H:%M:%S')
    context_dict['visits'] = visits
    context_dict['last_visit'] = last_visit_time
    return render(request,'rango/about.html',context=context_dict)


def show_category(request,category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    return render(request, 'rango/category.html', context_dict)

@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=True)
            print(category, category.slug)
            return index(request)
        else:
            print(form.errors)
    return render(request,'rango/add_category.html',{'form':form})

@login_required
def add_page(request,category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category =category
                page.views = 0
                page.save()
                return show_category(request,category_name_slug)
        else:
            print(form.errors)
    context_dict = {'form':form,'category':category}
    return render(request,'rango/add_page.html',context_dict)


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm
        profile_form = UserProfileForm
    context_dict = {'user_form':user_form,'profile_form':profile_form,'registered':registered}
    return render(request,'rango/register.html',context=context_dict)


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print("Invalid login details: {0} {1}".format(username,password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request,'rango/login.html',{})

@login_required
def restricted(request):
    return HttpResponse("Since you're logged in,you can see this text!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

tango_with_django_project/templates/rango/about-old.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <title>About</title>
    <body>
        <div>
            <h1>This tutorial has been put together by {{ your_name }}</h1>
        </div>
        <div>
            <!-- <a href="/rango/">Index</a><br /> -->
            <a href="{% url 'index' %}">Index</a><br />
            <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
        </div>
    </body>
</html>

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
    <h1>
        This tutorial has been put together by: {{ your_name }}
    </h1>
        Method:  {{ method }}<br />User:  {{ user }}<br />Visits:  {{ visits }}<br />Visits_time:  {{ last_visit }}
    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    </div>
{% endblock %}

tango_with_django_project/templates/rango/add_category-old.html
<!DOCTYPE html>
<html>
    <head>
        <title>Rango</title>
    </head>
    <body>
        <h1>Add a Category</h1>
        <div>
            <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fileds %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }} <br />
                    {{ field }}
                {% endfor %}
                <input type="submit" name="submit" value="Create Category"/>
            </form>
        </div>
    </body>
</html>

tango_with_django_project/templates/rango/add_category.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}

{% block title_block %}
    Add new category
{% endblock %}

{% block body_block %}
    <div>
        <br/>
        <form id="add_category" method="POST" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }} <br />
                {{ field }}<br/>
            {% endfor %}
            <br/>
            <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
        </form>
    </div>
{% endblock %}

tango_with_django_project/templates/rango/add_page-old.html
<!DOCTYPE html>
<html>
    <title>Rango</title>
    <body>
        {% if category %}
            <h1>Add a Page to {{ category.slug }}</h1>
            <div>
                <form id="page_form" method="POST" action="{% url 'rango:add_page' category.slug %}">
                    {% csrf_token %}
                    {% for hidden in form.hidden_fileds %}
                        {{ hidden }}
                    {% endfor %}
                    {% for field in form.visible_fields %}
                        {{ field.errors }}
                        {{ field.help_text }} <br />
                        {{ field }} <br />
                    {% endfor %}
                    <input type="submit" name="submit" value="Add Page"/>
                </form>
            </div>
        {% else %}
            <h2>The specified category does not exist!</h2>
        {% endif %}
    </body>
</html>

tango_with_django_project/templates/rango/add_page.html
{% extends 'rango/base_bootstrap.html' %}

{% block title_block %}
    Add new page
{% endblock %}

{% block body_block %}
    {% if category %}
        <br/>
        <h2 class="form-signin-heading">Add a page to {{ category.name }}</h2>
        <form id="add_page" method="POST" action="{% url 'rango:add_page' category.slug %}" >
            {% csrf_token %}
            {% for hidden in form.hidden_fileds %}
                        {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }} <br />
                {{ field }} <br />
            {% endfor %}
            <br/>
            <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
        </form>
    {% else %}
        <br/>
        <h2  class="form-signin-heading">The specified category does not exist!</h2>
    {% endif %}
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
    <head>
        <meta charset="UTF-8"/>
        <title>
            Rango-
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'rango:restricted' %}">Restricted</a> </li>
                    <!--<li><a href="{% url 'rango:logout' %}">Logout</a> </li>-->
                    <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a> </li>
                    <li><a href="/accounts/password/change/">Change Password</a> </li>
                    <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
                {% else %}
                    <!--<li><a href="{% url 'rango:register' %}">Register</a> </li>-->
                    <li><a href="{% url 'registration_register' %}">Register</a> </li>
                    <!--<li><a href="{% url 'rango:login' %}">Login</a> </li>-->
                    <li><a href="{% url 'auth_login' %}">Login</a> </li>
                {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a> </li>
                <li><a href="{% url 'rango:index' %}">Index</a> </li>
            </ul>
        </div>
    </body>
</html>

tango_with_django_project/templates/rango/base_bootstrap.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'js/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'js/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'js/jumbotron.css' %}" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Rango</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
          {% else %}
          <a class="nav-link" href="{% url 'auth_login' %}?next=/rango/">Login</a>
          {% endif %}
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'rango:index' %}">
                  <span data-feather="home"></span>
                  Index <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:about' %}">
                  <span data-feather="file"></span>
                  About
                </a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:restricted' %}">
                  <span data-feather="shopping-cart"></span>
                  Restricted
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/accounts/password/change/">
                  <span data-feather="users"></span>
                  Change Password
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:add_category' %}">
                  <span data-feather="bar-chart-2"></span>
                  Add New Category
                </a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'registration_register' %}">
                  <span data-feather="layers"></span>
                  Register Here
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_login' %}">
                  <span data-feather="users"></span>
                  Login
                </a>
              </li>
              {% endif %}
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Saved reports</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Current month
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Last quarter
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Social engagement
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Year-end sale
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <br />
            {% block body_block %}
            {% endblock %}
            <p class="mt-5 mb-3 text-muted text-center">&copy; 2017-2018</p>
        </main>

      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'js/jquery-slim.min.js' %}"><\/script>')</script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

  </body>
</html>

tango_with_django_project/templates/rango/category-old.html
<!DOCTYPE html>
<html>
    <title>Rango</title>
    <body>
        <div>
            {% if category %}
                <h1>{{ category.name }}</h1>
                {% if pages %}
                    <ul>
                        {% for page in pages %}
                            <li><a href="{{ page.url }}">{{ page.title }}</a> </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong>No pages currently in category.</strong>
                {% endif %}
                <div>
                    <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
                </div>
            {% else %}
                The specified category does not exist!
            {% endif %}
        </div>
    </body>
</html>

tango_with_django_project/templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
                <li>
                    <strong>
                        <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                    </strong>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no category present.</strong></li>
    {% endif %}
</ul>

tango_with_django_project/templates/rango/index-before12.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}

{% block title_block %}
    Index
{% endblock %}

{% block body_block %}
    <h1>Rango says ...</h1>
    <div>
        hey there partner!
    </div>
    <h2>Most Liked Categories</h2>
    <div>
        {% if categories %}
            <ul>
                {% for category in categories %}
                    <li><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}}
            <h2>There are no categories present.</h2>
        {% endif %}
    </div>
    <div>
        <h2>Most Viewed Pages</h2>
        <div>
            {% if pages %}
                <ul>
                    {% for page in pages %}
                        <li><a href="{{ page.url }}">{{ page.title }}</a> </li>
                    {% endfor %}
                </ul>
            {% else %}
                <h2>There are no pages present.</h2>
            {% endif %}
        </div>
    </div>
    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of rango" />
    </div>
{% endblock %}

tango_with_django_project/templates/rango/index-old.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>Rango</title>
    </head>
    <body>
        <h1>Rango says...</h1>
        <div>
            hey there partner!
        </div>
        <h2>Most Liked Categories</h2>
        <div>
            {% if categories %}
            <ul>
                {% for category in categories %}
                    <li>
                        <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>There are no categories present.</strong>
            {% endif %}
        </div>
        <h2>Most Viewed Pages</h2>
        <div>
            {% if pages %}
            <ul>
                {% for page in pages %}
                    <li>
                        <a href="{{ page.url }}">{{ page.title }}</a>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>There are no pages present.</strong>
            {% endif %}
        </div>
        <div>
            <a href="{% url 'rango:about' %}">About</a><br />
        </div>
        <div>
            <a href="{% url 'rango:add_category' %}">Add a New Category</a><br />
        </div>
        <div>
            <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
        </div>
    </body>
</html>

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}

{% block title_block %}
    Index
{% endblock %}

{% block body_block %}
    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="jumbotron">
            <div class="container">
                <h1 class="display-3">Rango says ...</h1>
                {% if user.is_authenticated %}
                    <p class="lead">hey there {{ user.username }}! </p>
                {% else %}
                    <p class="lead">hey there partner! </p>
                {% endif %}
                <p><a class="btn btn-primary btn-lg" href="{% url 'rango:about' %}" role="button">Learn more &raquo;</a></p>
            </div>
        </div>

        <div class="container">
            <!-- Example row of columns -->
            <div class="row">
                <div class="col-md-6">
                    <h2>Most Liked Categories</h2>
                    <p>
                        {% if categories %}
                            <ul class="list-group">
                                {% for category in categories %}
                                    <li class="list-group-item"><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        {% else %}}
                            <h2>There are no categories present.</h2>
                        {% endif %}
                    </p>
                </div>
                <div class="col-md-6">
                    <h2>Most Viewed Pages</h2>
                    <p>
                        {% if pages %}
                            <ul class="list-group">
                                {% for page in pages %}
                                    <li class="list-group-item"><a href="{{ page.url }}">{{ page.title }}</a> </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <h2>There are no pages present.</h2>
                        {% endif %}
                    </p>
                </div>
            </div>
            <hr>
        </div> <!-- /container -->
    </main>
    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of rango" />
    </div>
{% endblock %}

tango_with_django_project/templates/rango/login.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login to Rango</h1>
    <form id="login_form" method="POST" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50"/><br />
        Password: <input type="password" name="password" value="" size="50"/><br/>
        <input type="submit" value="登陆" />
    </form>
{% endblock %}